//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTask2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Circulation
    {
        public int Id { get; set; }
        public double Debit { get; set; }
        public double Credit { get; set; }
    
        public virtual Sheet Sheet { get; set; }
    }
}
