//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTask2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sheet
    {
        public int Id { get; set; }
        public string Class { get; set; }
        public int FileId { get; set; }
    
        public virtual DataFile DataFile { get; set; }
        public virtual Circulation Circulation { get; set; }
        public virtual OpeningBalance OpeningBalance { get; set; }
        public virtual ClosingBalance ClosingBalance { get; set; }
    }
}
