//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTask2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestDBEntities : DbContext
    {
        public TestDBEntities()
            : base("name=TestDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Circulation> Circulations { get; set; }
        public virtual DbSet<ClosingBalance> ClosingBalancies { get; set; }
        public virtual DbSet<OpeningBalance> OpeningBalancies { get; set; }
        public virtual DbSet<Sheet> Sheets { get; set; }
        public virtual DbSet<DataFile> DataFiles { get; set; }
    }
}
